import type { MenuCategory, MenuProduct } from "./types";

export const CATEGORIES: MenuCategory[] = [
  {
    id: "wings",
    label: "Wings",
    tagline: "Crispy chaos, extra sauce.",
    accent: "orange",
  },
  {
    id: "burgers",
    label: "Burgers",
    tagline: "Smash, stack, glitch.",
    accent: "green",
  },
  {
    id: "tacos",
    label: "Tacos",
    tagline: "Street heat, neon bite.",
    accent: "orange",
  },
  {
    id: "snacks",
    label: "Snacks",
    tagline: "Bar bites for winners.",
    accent: "green",
  },
  {
    id: "games",
    label: "Games",
    tagline: "Buy it. Share the code. Start when the food arrives.",
    accent: "orange",
  },
  {
    id: "drinks",
    label: "Drinks",
    tagline: "Cold drinks. Hot dares.",
    accent: "orange",
  },
  {
    id: "dessert",
    label: "Dessert",
    tagline: "Sweet… then spicy.",
    accent: "green",
  },
];

export const PRODUCTS: MenuProduct[] = [
  {
    id: "w1",
    categoryId: "wings",
    name: "Neon Buffalo Wings",
    description: "Classic buffalo, lime zest, blue-cheese dip.",
    priceCents: 1399,
    heat: 3,
    isAvailable: true,
    image: "/menu/chili-cheese-nuggets.png",
  },
  {
    id: "w2",
    categoryId: "wings",
    name: "Flinch Roulette Wings",
    description: "One wing is unreasonably spicy. Roll the dice.",
    priceCents: 1599,
    heat: 4,
    isAvailable: true,
    image: "/menu/mozzarella-sticks.png",
  },
  {
    id: "b1",
    categoryId: "burgers",
    name: "Electric Smash Burger",
    description: "Double smash, cheddar, pickles, house neon sauce.",
    priceCents: 1699,
    heat: 2,
    isAvailable: true,
    image: "/menu/veggie-burger.png",
  },
  {
    id: "b2",
    categoryId: "burgers",
    name: "Warning Yellow Jalapeño Burger",
    description: "Pepper jack, jalapeño jam, crispy onions.",
    priceCents: 1799,
    heat: 3,
    isAvailable: true,
    image: "/menu/jalapeno-bites.png",
  },
  {
    id: "t1",
    categoryId: "tacos",
    name: "Pink Carnitas Tacos",
    description: "Slow pork, pickled onion, salsa verde, lime.",
    priceCents: 1299,
    heat: 2,
    isAvailable: true,
    image: "/menu/jalapeno-bites.png",
  },
  {
    id: "t2",
    categoryId: "tacos",
    name: "Blue Heat Shrimp Tacos",
    description: "Chili shrimp, slaw, crema, hot oil.",
    priceCents: 1499,
    heat: 4,
    isAvailable: true,
    image: "/menu/chili-cheese-nuggets.png",
  },
  {
    id: "s1",
    categoryId: "snacks",
    name: "Arcade Nachos",
    description: "Cheese, pico, jalapeños, guac, neon drizzle.",
    priceCents: 1199,
    heat: 2,
    isAvailable: true,
    image: "/menu/chili-cheese-nuggets.png",
  },
  {
    id: "s2",
    categoryId: "snacks",
    name: "Stadium Fries",
    description: "Crispy fries, seasoning dust, spicy ketchup.",
    priceCents: 699,
    heat: 1,
    isAvailable: true,
    image: "/menu/mozzarella-sticks.png",
  },
  {
    id: "game_not_a_glitch",
    categoryId: "games",
    name: "Not a Flinch (Table Game)",
    description:
      "12-bite appetizer challenge. 2 bites are extra spicy. Create a room after you order.",
    priceCents: 1999,
    heat: 0,
    isAvailable: true,
    image: "/hero/no-flinch-product.png",
  },
  {
    id: "d1",
    categoryId: "drinks",
    name: "Electric Blue Lemonade",
    description: "Citrus + a tiny glitch. (Non-alcoholic)",
    priceCents: 549,
    heat: 0,
    isAvailable: true,
    image: "/menu/veggie-burger.png",
  },
  {
    id: "d2",
    categoryId: "drinks",
    name: "Hot Pink Mocktail",
    description: "Berry fizz, mint, lime, shimmering ice.",
    priceCents: 649,
    heat: 0,
    isAvailable: true,
    image: "/menu/jalapeno-bites.png",
  },
  {
    id: "ds1",
    categoryId: "dessert",
    name: "Neon Churros",
    description: "Cinnamon sugar, chocolate dip, chili salt option.",
    priceCents: 799,
    heat: 1,
    isAvailable: true,
    image: "/menu/chili-cheese-nuggets.png",
  },
];

export function getProductById(id: string) {
  return PRODUCTS.find((p) => p.id === id) ?? null;
}

